bindkey -r "^H"  # Unbind Ctrl+h
bindkey -r "^J"  # Unbind Ctrl+j
bindkey -r "^K"  # Unbind Ctrl+k
bindkey -r "^L"  # Unbind Ctrl+l

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="takashiyoshida"

plugins=(
	git
	zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

alias vim='nvim'
alias ll='ls -l'

export PATH="$PATH:$HOME/.local/bin:$HOME/go/bin:/usr/local/go/bin:$HOME/.cargo/bin/"

# Source machine/OS-specific config if it exists
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"

eval "$(direnv hook zsh)"

autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/bao bao
