bindkey -r "^H"  # Unbind Ctrl+h
bindkey -r "^J"  # Unbind Ctrl+j
bindkey -r "^K"  # Unbind Ctrl+k
bindkey -r "^L"  # Unbind Ctrl+l

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="takashiyoshida"

plugins=(
	git
	zsh-autosuggestions
)

source $ZSH/oh-my-zsh.sh

alias vim='nvim'
alias ll='ls -l'
alias ls='colorls'

export PATH="$PATH:$HOME/.local/bin:$HOME/go/bin"

set -o vi
bindkey -M viins '^F' autosuggest-accept

# Source machine/OS-specific config if it exists
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
